

<span class="copyright-year">
	<span>Original articles on this site are CC 
<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode">BY-NC-SA</a> 
licensed unless otherwise stated.</span>

<br>

    <small class="power-by">
        {{ __('footer.powered', '<a href="https://hexo.io/">Hexo</a> and <a href="https://github.com/frostfan/hexo-theme-polarbear">Polar Bear</a>') }}
    </small>
</span>
